/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2024-04-06 10:11:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "master/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<p class=\"title\">교과목 추가</p>\r\n");
      out.write("\t<form action=\"/courseInsert\" method=\"post\" name=\"frm\">\r\n");
      out.write("\t\t\t<table width=\"600px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>과목코드</td>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\"  name=\"id\" id=\"id\" ></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>과목명</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>학점</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"credit\" name=\"credit\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>담당강사</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select id=\"lecturer\" name=\"lecturer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">담당강사선택</option>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">김교수</option>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">이교수</option>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">박교수</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">추교수</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"5\">최교수</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"6\">임교슈</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>요일</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"week\" name=\"week\" value=\"1\">월요일\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"week\" name=\"week\" value=\"2\">화요일\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"week\" name=\"week\" value=\"3\">수요일\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"week\" name=\"week\" value=\"4\">목요일\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" id=\"week\" name=\"week\" value=\"5\">금요일\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>시작시간</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"start_hour\" name=\"start_hour\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>종료시간</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"number\" id=\"end_hour\" name=\"end_hour\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"추가\" onclick=\"return checkForm()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"목록\" onclick=\"location.href ='/courseList'\">\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\t\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction checkForm() {\r\n");
      out.write("\t\tif(document.frm.id.value.trim() == \"\"){\r\n");
      out.write("\t\t\talert('참가번호가 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.id.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.frm.name.value.trim() == \"\"){\r\n");
      out.write("\t\t\talert('참가자명가 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.name.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.frm.credit.value.trim() == \"\"){\r\n");
      out.write("\t\t\talert('생년월일이 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.credit.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.frm.lecture.value == 0){\r\n");
      out.write("\t\t\talert('성별이 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.lecture.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.frm.week.value > 5){\r\n");
      out.write("\t\t\talert('요일이 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.week.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.frm.start_hour.value.trim() == \"\"){\r\n");
      out.write("\t\t\talert('소속사 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.start_hour.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.frm.end_hour.value.trim() == \"\"){\r\n");
      out.write("\t\t\talert('소속사 입력되지 않았습니다!');\r\n");
      out.write("\t\t\tdocument.frm.end_hour.focus();\r\n");
      out.write("\t\t\tretuen false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.frm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "master/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
